In [1]:
import numpy

In [2]:
import numpy as np

# Question 1

In [3]:
numpy.arange(start=2, stop=51, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Question 2

In [4]:
lst = [] 
for i in range(0, 5): 
    ele = int(input()) 
  
    lst.append(ele) # adding the element 
    arr = numpy.asarray(lst)
      
print(arr)

lst1 = [] 
for i in range(0, 5): 
    ele = int(input()) 
  
    lst1.append(ele) # adding the element 
    arr1 = numpy.asarray(lst1)
      
print(arr1)
lst.extend(lst1) 
print ("Concatenated list using list.extend() : "
                               + str(lst))
arr.sort()
print(arr)
arr1.sort()
print(arr1)

1
8
9
5
6
[1 8 9 5 6]
12
16
11
10
13
[12 16 11 10 13]
Concatenated list using list.extend() : [1, 8, 9, 5, 6, 12, 16, 11, 10, 13]
[1 5 6 8 9]
[10 11 12 13 16]


# Question 3

In [5]:
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 
  
  
print("Enter the entries in a single line ") 
  
entries = list(map(int, input().split())) 
  
# For printing the matrix 
arr = np.array(entries).reshape(R, C) 
print(arr)
print(np.size(arr))
print(np.shape(arr))


Enter the number of rows:3
Enter the number of columns:3
Enter the entries in a single line 
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)


# Question 4

In [6]:
a=np.array([1,2,3,4,5,6,7,8])

In [7]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
a.shape

(8,)

In [9]:
b=a.reshape(2,4)

In [10]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
b=a[np.newaxis,:] #new dimension is added row wise

In [12]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [13]:
b.shape

(1, 8)

In [14]:
b=a[:,np.newaxis]#new dimension is addded column wise

In [15]:
b.shape

(8, 1)

In [16]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [18]:
a=np.array([1,2,3,4])

In [19]:
b=np.expand_dims(a,axis=0)

In [20]:
b

array([[1, 2, 3, 4]])

In [21]:
b=np.expand_dims(a,axis=(0,1))#new columns are added

In [22]:
b

array([[[1, 2, 3, 4]]])

In [23]:
a

array([1, 2, 3, 4])

# Question 5

In [24]:
np2d_one = np.array( [ [1,2] , [3,4] ]) 
np2d_two= np.array( [ [5,6] , [7,8] ] )

In [25]:
print ((np2d_one,np2d_two))

(array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]))


In [26]:
np.vstack((np2d_one,np2d_two))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
np.hstack((np2d_one,np2d_two))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Question 6

In [28]:
a_list = [1,1,4,5,9,4]
a_set = set(a_list)
number_of_unique_values = len(a_set)
print(number_of_unique_values)

4
